version: '3.8'

services:
  seculite:
    build: .
    image: seculite:latest
    container_name: seculite
    environment:
      - ZAP_TARGET=http://host.docker.internal:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./results:/seculite/results
      - ./logs:/seculite/logs
      - /home/fr4iser/Documents/Development/FoundryCord/:/target:ro
    #  - /absolute/path/to/your/codebase:/target:ro    #  - /absolute/path/to/your/codebase:/target:ro
    # Uncomment and set the following if you want to scan a different path
    # environment:
    #   - TARGET_PATH=/target 

  zap-webui:
    image: seculite:latest
    container_name: zap-webui
    entrypoint:
      - /opt/ZAP_2.16.1/zap.sh
      - -daemon
      - -host
      - 0.0.0.0
      - -port
      - "8080"
      - -config
      - api.addrs.addr.name=.*
      - -config
      - api.addrs.addr.regex=true
      - -config
      - api.disablekey=true
    ports:
      - "8080:8080"
    volumes:
      - ./results:/seculite/results
      - ./logs:/seculite/logs
      - /home/fr4iser/Documents/Development/FoundryCord/:/target:ro
