version: '3.8'

services:
  seculite:
    build: .
    image: seculite:latest
    container_name: seculite
    env_file:
      - .env
    environment:
      - ZAP_TARGET=${TARGET_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${REPORT_PATH}:/seculite/results
      - ${LOG_PATH}:/seculite/logs
      - ${TARGET_PATH}:/target:ro
    networks:
      - ${DOCKER_NETWORK}

  zap-webui:
    image: seculite:latest
    container_name: zap-webui
    env_file:
      - .env
    entrypoint:
      - /opt/ZAP_2.16.1/zap.sh
      - -daemon
      - -host
      - 0.0.0.0
      - -port
      - "${ZAP_WEBUI_PORT}"
      - -config
      - api.addrs.addr.name=.*
      - -config
      - api.addrs.addr.regex=true
      - -config
      - api.disablekey=true
    ports:
      - "${ZAP_WEBUI_PORT}:${ZAP_WEBUI_PORT}"
    volumes:
      - ${REPORT_PATH}:/seculite/results
      - ${LOG_PATH}:/seculite/logs
      - ${TARGET_PATH}:/target:ro
    networks:
      - ${DOCKER_NETWORK}

  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["python3", "web/app.py"]
    volumes:
      - ./results:/results
      - ./scripts:/scripts
    ports:
      - "5000:5000"
    working_dir: /seculite
    depends_on:
      - seculite

networks:
  bridge:
    driver: bridge
