version: '3.8'

services:
  scanner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: 1.0.0
    container_name: SimpleSecCheck_scanner_v1.0.0
    volumes:
      - ./results:/SimpleSecCheck/results
      - ./logs:/SimpleSecCheck/logs
      - ./conf:/SimpleSecCheck/conf
      - ./rules:/SimpleSecCheck/rules
      - ./trivy:/SimpleSecCheck/trivy
      - ./zap:/SimpleSecCheck/zap
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TARGET_URL=${TARGET_URL:-http://host.docker.internal:8000}
      - TARGET_PATH_IN_CONTAINER=${TARGET_PATH_IN_CONTAINER:-/target}
      - RESULTS_DIR_IN_CONTAINER=/SimpleSecCheck/results
      - LOGS_DIR_IN_CONTAINER=/SimpleSecCheck/logs
      - SEMGREP_RULES_PATH_IN_CONTAINER=/SimpleSecCheck/rules
      - TRIVY_CONFIG_PATH_IN_CONTAINER=/SimpleSecCheck/trivy/config.yaml
      - ZAP_CONFIG_PATH_IN_CONTAINER=/SimpleSecCheck/zap/baseline.conf
      - TRIVY_SCAN_TYPE=fs
      - FP_WHITELIST_FILE=/SimpleSecCheck/conf/fp_whitelist.json
    command: ["bash", "/SimpleSecCheck/scripts/security-check.sh"]
    networks:
      - SimpleSecCheck_network
    restart: "no"

networks:
  SimpleSecCheck_network:
    driver: bridge

volumes:
  results_data:
  logs_data:
