#!/usr/bin/env python3
"""
Script to switch between authentication modes in SimpleSecCheck.

This script helps you easily switch between FREE, BASIC, and JWT authentication modes
by updating the .env file and providing instructions for deployment.
"""

import os
import sys
import argparse
import subprocess
from pathlib import Path


class AuthModeSwitcher:
    """Switch between authentication modes."""
    
    def __init__(self):
        self.env_file = Path(".env")
        self.env_example = Path("env.example")
    
    def read_env_file(self) -> dict:
        """Read current .env file."""
        env_vars = {}
        if self.env_file.exists():
            with open(self.env_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        env_vars[key.strip()] = value.strip()
        return env_vars
    
    def write_env_file(self, env_vars: dict):
        """Write updated .env file."""
        with open(self.env_file, 'w') as f:
            # Write header
            f.write("# SimpleSecCheck Environment Configuration\n")
            f.write("# Generated by switch_auth_mode.py\n")
            f.write("#\n\n")
            
            # Write authentication mode
            f.write("# Authentication Mode Configuration\n")
            f.write(f"AUTH_MODE={env_vars.get('AUTH_MODE', 'free')}\n")
            f.write(f"LOGIN_REQUIRED={env_vars.get('LOGIN_REQUIRED', 'false')}\n")
            f.write(f"SESSION_SECRET={env_vars.get('SESSION_SECRET', 'your-session-secret-key-here')}\n")
            f.write("\n")
            
            # Write other variables (excluding auth mode ones)
            for key, value in env_vars.items():
                if key not in ['AUTH_MODE', 'LOGIN_REQUIRED', 'SESSION_SECRET']:
                    f.write(f"{key}={value}\n")
    
    def generate_session_secret(self) -> str:
        """Generate a secure session secret."""
        import secrets
        import string
        
        alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
        secret = ''.join(secrets.choice(alphabet) for _ in range(64))
        return secret
    
    def set_free_mode(self):
        """Configure for FREE mode."""
        print("🔧 Configuring for FREE Mode...")
        print("   - Public access, no login required")
        print("   - Everyone gets automatic session")
        print("   - Perfect for public security scanning services")
        
        env_vars = self.read_env_file()
        
        # Set authentication mode variables
        env_vars['AUTH_MODE'] = 'free'
        env_vars['LOGIN_REQUIRED'] = 'false'
        
        # Generate session secret if not exists
        if 'SESSION_SECRET' not in env_vars or env_vars['SESSION_SECRET'] == 'your-session-secret-key-here':
            env_vars['SESSION_SECRET'] = self.generate_session_secret()
            print(f"   - Generated new session secret: {env_vars['SESSION_SECRET'][:20]}...")
        
        self.write_env_file(env_vars)
        print("   ✅ .env file updated for FREE mode")
    
    def set_basic_mode(self):
        """Configure for BASIC mode."""
        print("🔧 Configuring for BASIC Mode...")
        print("   - Username/password login required")
        print("   - Session-based authentication")
        print("   - Perfect for corporate environments")
        
        env_vars = self.read_env_file()
        
        # Set authentication mode variables
        env_vars['AUTH_MODE'] = 'basic'
        env_vars['LOGIN_REQUIRED'] = 'true'
        
        # Generate session secret if not exists
        if 'SESSION_SECRET' not in env_vars or env_vars['SESSION_SECRET'] == 'your-session-secret-key-here':
            env_vars['SESSION_SECRET'] = self.generate_session_secret()
            print(f"   - Generated new session secret: {env_vars['SESSION_SECRET'][:20]}...")
        
        self.write_env_file(env_vars)
        print("   ✅ .env file updated for BASIC mode")
    
    def set_jwt_mode(self):
        """Configure for JWT mode."""
        print("🔧 Configuring for JWT Mode...")
        print("   - Token-based authentication")
        print("   - Enterprise SSO integration")
        print("   - Perfect for enterprise environments")
        
        env_vars = self.read_env_file()
        
        # Set authentication mode variables
        env_vars['AUTH_MODE'] = 'jwt'
        env_vars['LOGIN_REQUIRED'] = 'true'
        
        # Generate session secret if not exists
        if 'SESSION_SECRET' not in env_vars or env_vars['SESSION_SECRET'] == 'your-session-secret-key-here':
            env_vars['SESSION_SECRET'] = self.generate_session_secret()
            print(f"   - Generated new session secret: {env_vars['SESSION_SECRET'][:20]}...")
        
        self.write_env_file(env_vars)
        print("   ✅ .env file updated for JWT mode")
    
    def show_current_mode(self):
        """Show current authentication mode."""
        env_vars = self.read_env_file()
        
        auth_mode = env_vars.get('AUTH_MODE', 'free')
        login_required = env_vars.get('LOGIN_REQUIRED', 'false')
        session_secret = env_vars.get('SESSION_SECRET', 'not set')
        
        print("📊 Current Authentication Configuration:")
        print(f"   AUTH_MODE: {auth_mode}")
        print(f"   LOGIN_REQUIRED: {login_required}")
        print(f"   SESSION_SECRET: {'set' if session_secret != 'not set' else 'not set'}")
        print()
        
        if auth_mode == 'free':
            print("   Mode: FREE (Public access, no login required)")
            print("   Features:")
            print("     ✅ No authentication required")
            print("     ✅ Automatic guest sessions")
            print("     ✅ Public security scanning")
            print("     ✅ Rate limited for abuse prevention")
        elif auth_mode == 'basic':
            print("   Mode: BASIC (Username/password required)")
            print("   Features:")
            print("     🔒 Username/password authentication")
            print("     ✅ Session-based security")
            print("     ✅ Controlled access")
            print("     ✅ User management capabilities")
        elif auth_mode == 'jwt':
            print("   Mode: JWT (Token-based authentication)")
            print("   Features:")
            print("     🔒 Token-based authentication")
            print("     ✅ Enterprise SSO integration")
            print("     ✅ Keycloak/Auth0/Azure AD support")
            print("     ✅ Enterprise-grade security")
        else:
            print(f"   Mode: {auth_mode} (Unknown mode)")
        
        print()
    
    def restart_services(self):
        """Restart Docker services to apply changes."""
        print("🔄 Restarting Docker services...")
        
        try:
            # Check if docker-compose is available
            result = subprocess.run(['docker', '--version'], capture_output=True, text=True)
            if result.returncode != 0:
                print("   ❌ Docker not found. Please install Docker and try again.")
                return False
            
            # Check if docker-compose.yml exists
            if not Path('docker-compose.yml').exists():
                print("   ❌ docker-compose.yml not found. Please run from the project root.")
                return False
            
            # Restart services
            print("   Stopping services...")
            subprocess.run(['docker-compose', 'down'], check=True)
            
            print("   Starting services...")
            subprocess.run(['docker-compose', 'up', '-d'], check=True)
            
            print("   ✅ Services restarted successfully")
            return True
            
        except subprocess.CalledProcessError as e:
            print(f"   ❌ Failed to restart services: {e}")
            return False
        except Exception as e:
            print(f"   ❌ Unexpected error: {e}")
            return False
    
    def show_usage_examples(self):
        """Show usage examples for the current mode."""
        env_vars = self.read_env_file()
        auth_mode = env_vars.get('AUTH_MODE', 'free')
        
        print("💡 Usage Examples:")
        print()
        
        if auth_mode == 'free':
            print("# FREE Mode - Start a scan without authentication")
            print("curl -X POST http://localhost:8080/api/v1/scans/ \\")
            print('  -H "Content-Type: application/json" \\')
            print('  -d \'{"name": "Public Scan", "scan_type": "repository", "target_url": "https://github.com/example/repo", "target_type": "git"}\'')
            print()
            print("# Check session info")
            print("curl http://localhost:8080/api/v1/auth/session")
            
        elif auth_mode == 'basic':
            print("# BASIC Mode - Login first")
            print("curl -X POST http://localhost:8080/api/v1/auth/login \\")
            print('  -H "Content-Type: application/json" \\')
            print('  -d \'{"email": "user@example.com", "password": "password123"}\'')
            print()
            print("# Then start a scan with the token")
            print("curl -X POST http://localhost:8080/api/v1/scans/ \\")
            print('  -H "Authorization: Bearer YOUR_TOKEN" \\')
            print('  -H "Content-Type: application/json" \\')
            print('  -d \'{"name": "Authenticated Scan", "scan_type": "repository", "target_url": "https://github.com/example/repo", "target_type": "git"}\'')
            
        elif auth_mode == 'jwt':
            print("# JWT Mode - Get token from your SSO provider")
            print("TOKEN=$(get-token-from-sso)")
            print()
            print("# Start a scan with JWT token")
            print("curl -X POST http://localhost:8080/api/v1/scans/ \\")
            print('  -H "Authorization: Bearer $TOKEN" \\')
            print('  -H "Content-Type: application/json" \\')
            print('  -d \'{"name": "Enterprise Scan", "scan_type": "repository", "target_url": "https://github.com/example/repo", "target_type": "git"}\'')
        
        print()
    
    def validate_configuration(self):
        """Validate the current configuration."""
        print("🔍 Validating configuration...")
        
        env_vars = self.read_env_file()
        
        # Check required variables
        required_vars = ['AUTH_MODE', 'SESSION_SECRET']
        missing_vars = []
        
        for var in required_vars:
            if var not in env_vars or not env_vars[var]:
                missing_vars.append(var)
        
        if missing_vars:
            print(f"   ❌ Missing required variables: {', '.join(missing_vars)}")
            return False
        
        # Validate AUTH_MODE
        auth_mode = env_vars['AUTH_MODE']
        if auth_mode not in ['free', 'basic', 'jwt']:
            print(f"   ❌ Invalid AUTH_MODE: {auth_mode}. Must be 'free', 'basic', or 'jwt'")
            return False
        
        # Validate SESSION_SECRET
        session_secret = env_vars['SESSION_SECRET']
        if len(session_secret) < 32:
            print(f"   ⚠️  SESSION_SECRET is too short. Use at least 32 characters.")
        
        print("   ✅ Configuration validation passed")
        return True


def main():
    """Main function."""
    parser = argparse.ArgumentParser(
        description="Switch between authentication modes in SimpleSecCheck",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python switch_auth_mode.py --mode free          # Switch to FREE mode
  python switch_auth_mode.py --mode basic         # Switch to BASIC mode
  python switch_auth_mode.py --mode jwt           # Switch to JWT mode
  python switch_auth_mode.py --status             # Show current mode
  python switch_auth_mode.py --restart            # Restart services
  python switch_auth_mode.py --validate           # Validate configuration
        """
    )
    
    parser.add_argument('--mode', choices=['free', 'basic', 'jwt'],
                       help='Set authentication mode')
    parser.add_argument('--status', action='store_true',
                       help='Show current authentication mode')
    parser.add_argument('--restart', action='store_true',
                       help='Restart Docker services')
    parser.add_argument('--validate', action='store_true',
                       help='Validate current configuration')
    parser.add_argument('--examples', action='store_true',
                       help='Show usage examples')
    parser.add_argument('--no-restart', action='store_true',
                       help='Skip service restart after mode change')
    
    args = parser.parse_args()
    
    switcher = AuthModeSwitcher()
    
    # Handle status command
    if args.status:
        switcher.show_current_mode()
        return
    
    # Handle validation command
    if args.validate:
        switcher.validate_configuration()
        return
    
    # Handle examples command
    if args.examples:
        switcher.show_usage_examples()
        return
    
    # Handle restart command
    if args.restart:
        switcher.restart_services()
        return
    
    # Handle mode switching
    if args.mode:
        print(f"🚀 Switching to {args.mode.upper()} Mode")
        print("=" * 50)
        
        # Show current mode
        switcher.show_current_mode()
        
        # Set new mode
        if args.mode == 'free':
            switcher.set_free_mode()
        elif args.mode == 'basic':
            switcher.set_basic_mode()
        elif args.mode == 'jwt':
            switcher.set_jwt_mode()
        
        # Validate configuration
        if not switcher.validate_configuration():
            print("❌ Configuration validation failed. Please fix the issues above.")
            return
        
        # Show usage examples
        switcher.show_usage_examples()
        
        # Restart services unless --no-restart is specified
        if not args.no_restart:
            print("💡 Tip: Use --no-restart to skip service restart")
            print()
            switcher.restart_services()
        else:
            print("⏭️  Skipping service restart (--no-restart specified)")
        
        print("🎉 Authentication mode switch completed!")
        print()
        print("📝 Next steps:")
        print("   1. Review the updated .env file")
        print("   2. Restart your services if not done automatically")
        print("   3. Test the new authentication mode")
        print("   4. Update any client applications if needed")
        
    else:
        # Show help if no arguments provided
        parser.print_help()


if __name__ == "__main__":
    main()