# Bandit Configuration for SimpleSecCheck
# Purpose: Configure Bandit for Python code security scanning

# Output formats
output_formats:
  - json
  - text

# Scan options
scan_options:
  # Aggressive mode (more thorough scan)
  aggressive: false
  
  # Show skipped tests
  show_skipped: true
  
  # Verbose output
  verbose: true
  
  # Exclude tests by ID
  exclude_tests: []
  
  # Severity threshold (low/medium/high)
  severity_threshold: low
  
  # Confidence threshold (low/medium/high)
  confidence_threshold: low

# Include test IDs to run
include_tests:
  - B101  # assert_used
  - B102  # exec_used
  - B103  # hardcoded_password
  - B104  # hardcoded_bind_all_interfaces
  - B105  # hardcoded_password_string
  - B106  # hardcoded_password_funcarg
  - B107  # hardcoded_password_default
  - B301  # blacklist_calls
  - B302  # blacklist_imports
  - B303  # blacklist_imports
  - B304  # blacklist_imports
  - B305  # blacklist_imports
  - B306  # blacklist_imports
  - B307  # blacklist_imports
  - B308  # blacklist_imports
  - B309  # blacklist_imports
  - B401  # import_telnetlib
  - B402  # import_ftplib
  - B403  # import_pickle
  - B404  # import_subprocess
  - B405  # import_xml_etree
  - B406  # import_xmlrpclib
  - B407  # import_pycrypto
  - B501  # request_with_no_cert_validation
  - B502  # ssl_with_no_version
  - B503  # ssl_with_bad_version
  - B504  # ssl_with_bad_defaults
  - B505  # weak_cryptographic_key
  - B506  # use_of_insecure_hash_func
  - B601  # shell_injection
  - B602  # shell_injection_subprocess
  - B603  # subprocess_with_shell_equals_true
  - B604  # any_other_function_with_shell_equals_true
  - B701  # jinja2_autoescape_false
  - B702  # use_of_mako_templates
  - B801  # darglint
  - B901  # return_in_finally
  - B902  # linebreak_before_final_yield_or_return
  - B903  # blacklist_imports

# Exclude patterns
exclude_patterns:
  - "*/test*"
  - "*/tests/*"
  - "*/__pycache__/*"
  - "*/venv/*"
  - "*/env/*"
  - "*/virtualenv/*"
  - "*/migrations/*"

# Report settings
report_settings:
  # Include detailed vulnerability information
  detailed: true
  
  # Show suppressed issues
  show_suppressed: false
  
  # Output format for reports
  output_format: json

# Integration settings
integration:
  # Exit code on vulnerabilities found
  exit_on_vulnerabilities: false
  
  # Include in HTML report
  include_in_html: true
  
  # Generate separate report files
  generate_files: true

