# Generated by Django 5.2.1 on 2025-05-11 21:08

from django.db import migrations

# Role names consistent with core/permissions.py
ROLE_ADMIN = 'Administrator'
ROLE_PROJECT_OWNER = 'Project Owner'
ROLE_PROJECT_MEMBER = 'Project Member'
ROLE_AUDITOR = 'Auditor'

ROLES_TO_CREATE = [
    ROLE_ADMIN,
    ROLE_PROJECT_OWNER,
    ROLE_PROJECT_MEMBER,
    ROLE_AUDITOR,
]

def create_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for role_name in ROLES_TO_CREATE:
        Group.objects.get_or_create(name=role_name)

def remove_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=ROLES_TO_CREATE).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apikey'),
        # It might also implicitly depend on auth app migrations being run first,
        # but Django handles this order for auth.Group model.
    ]

    operations = [
        migrations.RunPython(create_default_groups, remove_default_groups),
    ]
