# Generated by Django 5.2.1 on 2025-05-11 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_create_default_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, help_text='ID of the Celery task processing this job', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_timestamp', models.DateTimeField(blank=True, help_text='When the scan execution actually started', null=True)),
                ('completed_timestamp', models.DateTimeField(blank=True, help_text='When the scan execution finished', null=True)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_scan_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='core.project')),
                ('scan_configuration', models.ForeignKey(blank=True, help_text='Configuration used for this job, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_jobs', to='core.scanconfiguration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(help_text='Name of the security tool that produced this result, e.g., Bandit', max_length=100)),
                ('summary_data', models.JSONField(blank=True, help_text='Summary of findings, e.g., severity counts', null=True)),
                ('raw_output', models.TextField(blank=True, help_text='Full raw output from the tool, if stored', null=True)),
                ('findings', models.JSONField(default=list, help_text='Structured list of findings/vulnerabilities')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the tool failed for this result part', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this specific result was recorded')),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.scanjob')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
