# Generated by Django 5.2.1 on 2025-05-11 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scanjob_scanresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanconfiguration',
            options={'ordering': ['project__name', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='scanconfiguration',
            unique_together={('project', 'name')},
        ),
        migrations.AddField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='', editable=False, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='last_used',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='has_predefined_targets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='target_details_json',
            field=models.JSONField(blank=True, help_text='Structured target info, e.g., repo URL, paths. Used if has_predefined_targets is true.', null=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='tool_configurations_json',
            field=models.JSONField(blank=True, help_text='Tool-specific settings, e.g., Bandit severity, Semgrep rules.', null=True),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='branch_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='ci_build_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='commit_hash',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='repository_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='triggered_by_ci',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional: Set an expiration date for the key.', null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(blank=True, help_text='A friendly name for this API key.', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='completed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='started_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('developer', 'Developer'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project__name', 'user__username'],
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='project_memberships', through='core.ProjectMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='hashed_key',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='last_used_at',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='scanconfiguration',
            name='scan_targets',
        ),
        migrations.RemoveField(
            model_name='scanconfiguration',
            name='schedule_options',
        ),
        migrations.RemoveField(
            model_name='scanconfiguration',
            name='security_tools',
        ),
        migrations.RemoveField(
            model_name='scanconfiguration',
            name='target_groups',
        ),
    ]
