# Generated by Django 5.0.14 on 2025-05-14 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_scanconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_tool_settings_json',
            field=models.JSONField(blank=True, help_text='Default tool settings JSON for scans in this project.', null=True),
        ),
        migrations.CreateModel(
            name='DefaultProjectTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name for this default target within the project (e.g., 'Main Codebase', 'Staging API').", max_length=255)),
                ('target_type', models.CharField(choices=[('path', 'File System Path'), ('url', 'URL'), ('git_repo', 'Git Repository'), ('docker_image', 'Docker Image')], help_text='Type of the default target.', max_length=20)),
                ('target_definition', models.TextField(help_text='The actual target definition (e.g., URL, path, repo URI).')),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary default target for the project? Only one target can be primary per project.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_targets', to='core.project')),
            ],
            options={
                'ordering': ['project__name', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
