# Generated by Django 5.0.14 on 2025-05-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_default_tool_settings_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_main_targets_json',
            field=models.JSONField(blank=True, default=dict, help_text='Main target definitions for the project (e.g., {"codebase_git": "git@example.com:repo.git", "web_url": "https://example.com"}).', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='default_tool_settings_json',
            field=models.JSONField(blank=True, default=dict, help_text='Default tool settings JSON for scans in this project (e.g., {"bandit": {"severity": "HIGH"}}).', null=True),
        ),
        migrations.DeleteModel(
            name='DefaultProjectTarget',
        ),
    ]
