# Generated by Django 5.0.14 on 2025-05-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_project_main_targets_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='target_info',
            field=models.JSONField(blank=True, help_text='The specific target information used for this scan job.', null=True),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='tool_settings',
            field=models.JSONField(blank=True, help_text='The specific tool settings used for this scan job.', null=True),
        ),
    ]
