name: SecuLite Security Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Semgrep
        run: pip install semgrep
      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget -qO- https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.49.1_Linux-64bit.deb > trivy.deb
          sudo dpkg -i trivy.deb
      - name: Install ZAP
        run: sudo apt-get install -y zaproxy
      - name: Run Security Check
        run: bash scripts/security-check.sh .
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: security-results
          path: results/ 